### ISSUE TITLE
Implement EIP-7498 as a component in Cairo 2.6

### ISSUE THREAD

**Issue by tekkac** [carbonable-labs/cairo-erc-7498#1]
**Description**
---
Implement [EIP-7498: NFT Redeemable](https://eips.ethereum.org/EIPS/eip-7498) in Cairo 2.6 based on the [Solidity Reference Implementation](https://github.com/ethereum/ERCs/tree/master/assets/erc-7498)

**Additional Information**
---------------------------
[Medium Difficult  - Cairo - Medium Priority]

**Acceptance Criteria**
---

- [ ] Implementation of a component-based EIP-7498

**Comment by AryanGodara** [comment]
@tekkac Can i quickly get started with this one, so I can start working on the unit tests?

**Comment by Khyati729** [comment]
Contribute to Carbonable during ODHack: 
Provable environmental infra

- Go to the CarbonableOD Telegram: https://t.me/carbonableOD
- Present yourself and tell us which issue you want to pick
- Explain shortly how you want to tackle the issue
- Ask a question if you need some clarity
- When you're selected you will be assigned to the issue

**Comment by saimeunt** [comment]
Hey @Khyati729 I'd like to work on this please.
