### ISSUE TITLE
Implement Starknet Foundry unit testing

### ISSUE THREAD

**Issue by tekkac** [carbonable-labs/cairo-erc-7498#2]
**Description**
---
Adapt and implement unit tests using Starknet Foundry in Cairo 2.6 from the [ERC specification implementation](https://github.com/ethereum/ERCs/tree/master/assets/erc-7498).

**Additional Information**
---------------------------
[Easy  - Cairo - Medium Priority]

**Acceptance Criteria**
---
- [ ] Add the Starknet Foundry dependency
- [ ] Adapt and pass unit tests from the Solidity implementation of [EIP-7498: NFT Redeemables](https://eips.ethereum.org/EIPS/eip-7498)

**Comment by AryanGodara** [comment]
@tekkac This issue is linked to #1, right?
So, before working on this, can I get started on implementing ERC7498?

**Comment by Khyati729** [comment]
Contribute to Carbonable during ODHack: 
Provable environmental infra

- Go to the CarbonableOD Telegram: https://t.me/carbonableOD
- Present yourself and tell us which issue you want to pick
- Explain shortly how you want to tackle the issue
- Ask a question if you need some clarity
- When you're selected you will be assigned to the issue

**Comment by Joy-Adah** [comment]
@tekkac can I be assigned to this?

**Comment by Khyati729** [comment]
@Joy-Adah  would you like to start working on this?
If yes, kindly please

- Go to the CarbonableOD Telegram: https://t.me/carbonableOD
- Explain shortly how you want to tackle the issue
- Ask a question if you need some clarity
- When you're selected you will be assigned to the issue

**Comment by aagbotemi** [comment]
@Khyati729 I'll like to take up this task

**Comment by TropicalDog17** [comment]
Hi @Khyati729 could I work on this issue?
