### ISSUE TITLE
Implement Starknet Foundry Integration tests

### ISSUE THREAD

**Issue by tekkac** [carbonable-labs/cairo-erc-7498#3]
**Description**
---
Adapt and implement integration tests using Starknet Foundry in Cairo 2.6 from the [ERC specification implementation](https://github.com/ethereum/ERCs/tree/master/assets/erc-7498).

**Additional Information**
---------------------------
[Medium Difficult  - Cairo - Medium Priority]

**Acceptance Criteria**
---
- [ ] Add the Starknet Foundry dependency
- [ ] Adapt and pass integration tests from the Solidity implementation of [EIP-7498: NFT Redeemables](https://eips.ethereum.org/EIPS/eip-7498)

**Comment by Khyati729** [comment]
Contribute to Carbonable during ODHack: 
Provable environmental infra

- Go to the CarbonableOD Telegram: https://t.me/carbonableOD
- Present yourself and tell us which issue you want to pick
- Explain shortly how you want to tackle the issue
- Ask a question if you need some clarity
- When you're selected you will be assigned to the issue

**Comment by HumbertoTM10** [comment]
Hi! I can take this issue

**Comment by Khyati729** [comment]
> Hi! I can take this issue

Hey, could you please Go to the CarbonableOD Telegram: https://t.me/carbonableOD
and follow the steps needed for me to assign the issue to you
